basePath: /
consumes:
- application/json
host: localhost
info:
  description: Documentation of our LibraryAPI. With this RestAPI you can make CRUD
    operations on Books and Authors.
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
  termsOfService: there are no TOS at this moment, use at your own risk we take no
    responsibility
  title: LibraryAPI.
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
swagger: "2.0"
